sudo: required

services:
    - docker

before_install:
    - docker build -t  chungisudocker/loginapp .

script:
    - docker run  chungisudocker/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push  chungisudocker/loginapp

deploy:
    provider: elasticbeanstalk
    region: ap-northeast-2
    app: docker-multi-container-app
    env: Dockermulticontainerapp-env-1
    version_label: "docker-multi-container-app-v1"
    bucket_name: elasticbeanstalk-ap-northeast-2-908885700562
    bucket_path: docker-multi-container-app

    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
